/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function runtimeStartCaptureInputProbe(): string
export declare function runtimePollCaptureInputProbe(): string
export declare function runtimeStopCaptureInputProbe(): string
export declare function runtimeStartEncoderInputProbe(): string
export declare function runtimePollEncoderInputProbe(): string
export declare function runtimeStartGlesBufferProbe(): string
export declare function runtimePollGlesBufferProbe(): string
export declare function runtimeStartNativeBufferProbe(): string
export declare function runtimePollNativeBufferProbe(): string

/** User-enabled view-only host; local approval + system recording consent required. */
/**
 * Adopts the native XComponent the Surface's `onLoad` hands over; 0 once held.
 */
export declare function xcomponentAttach(context: object): number
/**
 * Declares the rate the video Surface is produced at, as a platform result code.
 *
 * Zero means the expectation was accepted, -3 that no component was adopted yet.
 */
export declare function xcomponentSetFrameRateRangeNative(expected: number, min: number, max: number): number
export declare function engineHostStart(width: number, height: number, fps: number): string
export declare function engineHostSnapshot(id: string): string
export declare function engineHostApprove(id: string, requestId: string, allow: boolean): boolean
export declare function engineHostRequestClose(id: string): void
/** Resolves only after Core teardown succeeds; failure retains the host owner. */
export declare function engineHostClose(id: string): Promise<void>
/** JSON with initialized id and public peer_signing_key_base64 only. */
export declare function engineHostIdentity(): string

/** Normal navigation keeps XComponent mounted; platform destruction must request close immediately. */
/** Privacy-gated one-time configuration with trusted Ability.filesDir; returns local ID. */
export declare function engineInitialize(appDir: string): string
export declare function engineConnect(surfaceId: string, address: string, username: string,
  localId: string, localName: string, password: string, fps: number): string
export declare function engineSnapshot(id: string): string
/** Strict out-of-band peer Ed25519 pin; never a server key or automatic TOFU. */
export declare function engineConnectVerified(surfaceId: string, address: string, username: string,
  localId: string, localName: string, password: string, requestedFps: number,
  expectedPeerId: string, peerSigningKeyBase64: string): string
/** Strict hbbs/hbbr ID route using initialized Config; no plaintext/TOFU fallback. */
export declare function engineConnectId(surfaceId: string, peerId: string, localId: string,
  localName: string, password: string, requestedFps: number): string
export declare function engineMouse(id: string, kind: number, button: number, x: number, y: number): boolean
/** Pending close retains the explicit NativeWindow reference; never force-free it. */
export declare function engineRequestClose(id: string): void
export declare function engineClose(id: string): Promise<void>
/** Actual HEVC metadata, advertised-only. No measured FPS/HDR/capture claim. */
export declare function engineCapabilities(): Promise<string>

/* Legacy declarations below exist for unloaded old UI compilation only. */
export declare function backendSummary(): string

export declare function buildMarker(): string

export declare function healthcheck(): string

export declare function controlledServerStart(configJson: string): Promise<string>
export declare function controlledServerStop(): Promise<string>
export declare function controlledServerGetStatus(): string
export declare function controlledIncomingPoll(limit: number): string
export declare function controlledIncomingResolve(requestId: string, accepted: boolean): string
export declare function controlledIncomingSetPermission(requestId: string, permission: string, enabled: boolean): string
export declare function controlledPasswordGet(): string
export declare function controlledPasswordRefresh(): string
export declare function controlledPasswordSetPermanent(password: string): string
export declare function controlledPasswordSetVerificationMethod(method: string): string
export declare function controlledSettingsGet(): string
export declare function controlledSettingSet(key: string, value: string): string
export declare function controlledTwoFactorGet(): string
export declare function controlledTwoFactorBegin(): string
export declare function controlledTwoFactorVerify(code: string): string
export declare function controlledTwoFactorDisable(): string
export declare function controlledTwoFactorRemoveTrustedDevices(hwidsJson: string): string
export declare function controlledTwoFactorClearTrustedDevices(): string
export declare function controlledScreenConfigure(configJson: string): string
export declare function controlledScreenCaptureStart(configJson: string): string
export declare function controlledScreenCaptureStop(): string
export declare function controlledScreenCaptureGetStatus(): string

export declare function inputInterceptorPollEvents(limit: number): string

export declare function inputInterceptorStart(): string

export declare function inputInterceptorStop(): string

export declare function nativeVersion(): string

export declare function runtimeGetApiServer(): string

export declare function runtimeGetAccountState(): string

export declare function runtimeGetAccountLoginOptions(): string

export declare function runtimeStartAccountLoginOptions(): string

export declare function runtimePollAccountLoginOptions(): string

export declare function runtimeStartAccountLogin(payloadJson: string): string

export declare function runtimeStartAccountOidc(provider: string): string

export declare function runtimePollAccountOidc(): string

export declare function runtimeCancelAccountOidc(): string

export declare function runtimeStartAccountVerification(payloadJson: string): string

export declare function runtimePollAccountAction(): string

export declare function runtimeAccountLogout(): string

export declare function runtimeCancelAccountChallenge(): string

export declare function runtimeStartAddressBookSync(): string

export declare function runtimePollAddressBookSync(): string

export declare function runtimeGetDecoderCapabilities(): string

export declare function runtimeGetServerConfig(): string

export declare function runtimeInit(appDir: string, deviceName: string): string

export declare function runtimeListAddressBookPeers(): string

export declare function runtimeListFavorites(): string

export declare function runtimeListLanPeers(): string

export declare function runtimeListLocalDir(path: string): string

export declare function runtimeListRecentPeers(): string

export declare function runtimeQueryPeerOnlineStates(peerIdsJson: string): Promise<string>

export declare function runtimeProbePeerDirectStates(targetsJson: string): Promise<string>

export declare function runtimeRemoveDiscoveredPeer(peerId: string): string

export declare function runtimeRemoveRecentPeer(peerId: string): string

export declare function runtimeScanLanPeers(): Promise<string>

export declare function runtimeSetFavorite(peerId: string, favorite: boolean): string

export declare function runtimeSetServerConfig(configJson: string): string

export declare function runtimeTestServerConfig(configJson: string): Promise<string>

export declare function sessionAdd(sessionId: string, peerTarget: string, optionsJson: string): string

export declare function sessionAlternativeCodecs(sessionId: string): string

export declare function sessionBindSurface(sessionId: string, display: number, surfaceId: string): string

export declare function sessionGetSoftwarePresentState(sessionId: string, display: number): string

export declare function sessionGetFrameRateSnapshot(sessionId: string, display: number): string

export declare function sessionGetNativeDecoderSnapshot(sessionId: string, display: number): string

export declare function sessionCancelJob(sessionId: string, actId: number): string

export declare function sessionChangeResolution(sessionId: string, display: number, width: number, height: number): string

export declare function sessionClose(sessionId: string): string

export declare function sessionEnterOrLeave(sessionId: string, enter: boolean): string

export declare function sessionGetConnToken(sessionId: string): string | null

export declare function sessionGetEnableTrustedDevices(sessionId: string): boolean

export declare function sessionGetImageQuality(sessionId: string): string | null

export declare function sessionGetRemoteAudioState(sessionId: string): string

export declare function sessionGetRgbaSize(sessionId: string, display: number): number

export declare function sessionGetToggleOption(sessionId: string, arg: string): boolean

export declare function sessionHandleFlutterKeyEvent(sessionId: string, keyJson: string): string

export declare function sessionInputKey(sessionId: string, keyJson: string): string

export declare function sessionInputString(sessionId: string, value: string): string

export declare function sessionLogin(sessionId: string, loginJson: string): string

export declare function sessionNextRgba(sessionId: string, display: number): void

export declare function sessionOnWaitingForImageDialogShow(sessionId: string): string

export declare function sessionPeerOption(sessionId: string, name: string, value: string): void

export declare function sessionPollEvents(sessionId: string, limit: number): string

export declare function sessionReadRemoteDir(sessionId: string, path: string, includeHidden: boolean): string

export declare function sessionReconnect(sessionId: string, forceRelay: boolean): string

export declare function sessionRefresh(sessionId: string, display: number): string

export declare function sessionSetVideoPaused(sessionId: string, paused: boolean): string

export declare function sessionSend2Fa(sessionId: string, code: string, trustThisDevice: boolean): string

export declare function sessionSendChat(sessionId: string, text: string): string

export declare function sessionSendClipboard(sessionId: string, content: string): string

export declare function sessionSendClipboardImage(sessionId: string, image: Uint8Array): string

export declare function sessionSendClipboardFiles(sessionId: string, pathsJson: string): string

export declare function sessionSetClipboardFileRoot(sessionId: string, root: string): string

export declare function sessionSendFiles(sessionId: string, actId: number, path: string, to: string, fileNum: number, includeHidden: boolean, isRemote: boolean, isDir: boolean): string

export declare function sessionSendMouse(sessionId: string, mouseJson: string): string

export declare function sessionSendMouseEvent(sessionId: string, eventKind: number, button: number, x: number, y: number, relativeMarker: number): boolean

export declare function sessionInputDeliveryStatus(sessionId: string): string

export declare function sessionSendNote(sessionId: string, note: string): void

export declare function sessionSendPointer(sessionId: string, pointerJson: string): string

export declare function sessionTakeClipboard(sessionId: string): string

export declare function sessionTakeClipboardImage(sessionId: string): Uint8Array

export declare function sessionSetCodecPreference(sessionId: string, codec: string): string

export declare function sessionSetCommon(sessionId: string, key: string, value: string): string

export declare function sessionSetConfirmOverrideFile(sessionId: string, actId: number, fileNum: number, needOverride: boolean, remember: boolean, isUpload: boolean): string

export declare function sessionSetCustomFps(sessionId: string, fps: number): string

export declare function sessionSetCustomImageQuality(sessionId: string, value: number): void

export declare function sessionSetImageQuality(sessionId: string, value: string): string

export declare function sessionSetShowRemoteCursor(sessionId: string, enabled: boolean): string

export declare function sessionSetSize(sessionId: string, display: number, width: number, height: number): string

export declare function sessionStart(sessionId: string): string

export declare function sessionSetViewOnly(sessionId: string, enabled: boolean): string

export declare function sessionSwitchDisplay(sessionId: string, displaysJson: string): string

export declare function sessionTakeRgbaFrame(sessionId: string, display: number): Uint8Array

export declare function sessionToggleOption(sessionId: string, arg: string): void

export declare function transferNextJobId(): number
